build_image:
  stage: build
  tags: [ "docker3" ]
  only:
    refs:
    - tags
    changes:
    - dockerfiles/**/*
    - .gitlab-ci.yml
  script:
  #- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - dockerfiles/build.sh
  - dockerfiles/push.sh
