stages:
  - build
  - push

.docker_images:
  tags: [ "docker3" ]
  only:
    refs:
    - tags
    changes:
    - dockerfiles/**/*
    - .gitlab-ci.yml
  before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build_images:
  stage: build
  extends: .docker_images
  script:
  - dockerfiles/build.sh

push_images:
  stage: push
  extends: .docker_images
  script:
  - dockerfiles/push.sh
