# Specified timezone should be existing by path
# /usr/share/zoneinfo/<timezone>

timezone:

# ------------------------------------------------------------------------------
# Persistent Volume configuration
# ------------------------------------------------------------------------------

persistence:

  # Volume for OpenNebula Database
  data:
    enabled: false
    accessModes:
    - ReadWriteOnce
    size: 10Gi
    storageClassName: default
    annotations: {}
    finalizers:
    - kubernetes.io/pvc-protection

    # Use existing PVC instead
    existingClaim:

  # OpenNebula Shared volume, used for sharing logs, novnc tokens
  # and as temporary storage for uploading images via Sunstone
  # necessary if you need these features
  shared:
    enabled: false

    accessModes:
    - ReadWriteMany
    size: 10Gi
    storageClassName: default
    annotations: {}
    finalizers:
    - kubernetes.io/pvc-protection

    # Use existing PVC instead
    existingClaim:

# ------------------------------------------------------------------------------
# Main OpenNebula daemon configuration
# ------------------------------------------------------------------------------

oned:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

  replicas: 3

  # Allow to bootsrap new cluster
  createCluster: 1

  image:
    repository: docker.io/kvaps/opennebula
    tag: tight-integration
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regsecret

  nodeSelector: {}
  tolerations: []

  # Specify passwords for default accounts
  oneadminPasswd:
  serveradminPasswd:
  oneKey:

  # Specify id_rsa private key for ssh connections
  sshKey:

  port: 2633
  service:
    labels: {}
    annotations: {}
    port: 2633

  # Database configuration
  db:
    enabled: true
    backend: mysql
    server: 127.0.0.1
    port: 3306
    user: oneadmin
    passwd: oneadmin
    dbName: opennebula
    connections: 50
    rootPasswd:

    image:
      repository: docker.io/library/mysql
      tag: 8.0.18
      pullPolicy: IfNotPresent

  # Specify nodePort for collectd service (30000-32767)
  # port and nodePort should be the same
  collectd:
    port: 32155
    nodePort: 32155

  ingress:
    enabled: true
    labels: {}
    annotations:
      #kubernetes.io/ingress.class: nginx
      #kubernetes.io/tls-acme: "true"
    hosts:
    - opennebula.example.org
    tls:
    - secretName: opennebula-tls
      hosts:
      - opennebula.example.org

  configOverrides:
    LOG:
      SYSTEM: file
      DEBUG_LEVEL: 3
  configAppends: {}

# ------------------------------------------------------------------------------
# OpenNebula scheduler configuration
# ------------------------------------------------------------------------------

sched:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/kvaps/opennebula
    tag: tight-integration
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regsecret

  nodeSelector: {}
  tolerations: []

  configOverrides:
    LOG:
      system: std
      debug_level: 3

# ------------------------------------------------------------------------------
# Sunstone server configuration
# ------------------------------------------------------------------------------

sunstone:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 3

  image:
    repository: docker.io/kvaps/opennebula-sunstone
    tag: v5.8.5-fix
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regsecret

  port: 9869
  service:
    labels: {}
    annotations: {}
    port: 9869

  ingress:
    enabled: true
    labels: {}
    annotations:
      #kubernetes.io/ingress.class: nginx
      #nginx.ingress.kubernetes.io/proxy-body-size: 5000m
      #kubernetes.io/tls-acme: "true"
    hosts:
    - opennebula.example.org
    tls:
    - secretName: opennebula-tls
      hosts:
      - opennebula.example.org

  configOverrides:
    :debug_level: 3

# ------------------------------------------------------------------------------
# NoVNC server configuration
# ------------------------------------------------------------------------------

novnc:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/kvaps/opennebula-sunstone
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regsecret

  port: 29876
  service:
    labels: {}
    annotations: {}
    port: 29876

  ingress:
    enabled: true
    labels: {}
    annotations:
      #kubernetes.io/ingress.class: nginx
      #kubernetes.io/tls-acme: "true"
    hosts:
    - opennebula.example.org
    tls:
    - secretName: opennebula-tls
      hosts:
      - opennebula.example.org

# ------------------------------------------------------------------------------
# Memcached server configuration
# ------------------------------------------------------------------------------

memcached:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/library/memcached
    tag: 1.5.6-alpine
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regsecret

  nodeSelector: {}
  tolerations: []

  port: 11211
  service:
    labels: {}
    annotations: {}
    port: 11211

# ------------------------------------------------------------------------------
# OneGate server configuration
# ------------------------------------------------------------------------------

gate:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/kvaps/opennebula-gate
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  nodeSelector: {}
  tolerations: []

  port: 5030
  service:
    labels: {}
    annotations: {}
    port: 5030

  # OneGate should use different domain unlike sunstone
  ingress:
    enabled: true
    labels: {}
    annotations:
      #kubernetes.io/ingress.class: nginx
      #kubernetes.io/tls-acme: "true"
    hosts:
    - opennebula-gate.example.org
    tls:
    - secretName: opennebula-tls
      hosts:
      - opennebula-gate.example.org

  configOverrides:
    :debug_level: 3

# ------------------------------------------------------------------------------
# OneFlow server configuration
# ------------------------------------------------------------------------------

flow:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/kvaps/opennebula-flow
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regsecret

  nodeSelector: {}
  tolerations: []

  port: 2474
  service:
    labels: {}
    annotations: {}
    port: 2474

  configOverrides:
    :debug_level: 2
