timezone: Europe/Prague

persistence:
  data:
    enabled: false
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    size: 10Gi
    annotations: {}
    finalizers:
    - kubernetes.io/pvc-protection
    existingClaim:

  shared:
    enabled: false
    storageClassName: default
    accessModes:
    - ReadWriteMany
    size: 10Gi
    annotations: {}
    finalizers:
    - kubernetes.io/pvc-protection
    existingClaim:


oned:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

  replicas: 3
  createCluster: 1

  image:
    repository: docker.io/kvaps/opennebula
    tag: tight-integration
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regsecret

  nodeSelector:
    node-role.kubernetes.io/master: ""
  
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

  oneadminPasswd: asdasdASD
  serveradminPasswd: vae7thailahh7kiexa2phaipooChah
  oneKey: chaizao3hie1chaiDathaej1puuFoo
  #sshKey:

  port: 2633
  service:
    labels: {}
    annotations: {}
    port: 2633

  # Database config
  db:
    enabled: true
    backend: mysql
    server: 127.0.0.1
    port: 3306
    user: oneadmin
    passwd: oneadmin
    dbName: opennebula
    connections: 50
    rootPasswd: vahch9saz6ogeaP4ou7P

    image:
      repository: docker.io/library/mysql
      tag: 8.0.18
      pullPolicy: IfNotPresent

  collectd:
    port: 32155
    nodePort: 32155

  ingress:
    enabled: true
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
      #kubernetes.io/tls-acme: "true"
    hosts:
    - opennebula.example.org
    tls:
    - secretName: opennebula-tls
      hosts:
      - opennebula.example.org

sched:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/kvaps/opennebula
    tag: tight-integration
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  nodeSelector:
    node-role.kubernetes.io/master: ""
  
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

sunstone:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 3

  image:
    repository: docker.io/kvaps/opennebula-sunstone
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  port: 9869
  service:
    labels: {}
    annotations: {}
    port: 9869

  ingress:
    enabled: true
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 5000m
      #kubernetes.io/tls-acme: "true"
    hosts:
      - opennebula.example.org
    tls:
      - secretName: opennebula-tls
        hosts:
          - opennebula.example.org

novnc:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/kvaps/opennebula-sunstone
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  port: 29876
  service:
    labels: {}
    annotations: {}
    port: 29876

  ingress:
    enabled: true
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
      #kubernetes.io/tls-acme: "true"
    hosts:
      - opennebula.example.org
    tls:
      - secretName: opennebula-tls
        hosts:
          - opennebula.example.org


memcached:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/library/memcached
    tag: 1.5.6-alpine
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  nodeSelector:
    node-role.kubernetes.io/master: ""
  
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

  port: 11211
  service:
    labels: {}
    annotations: {}
    port: 11211

gate:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/kvaps/opennebula-gate
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  nodeSelector:
    node-role.kubernetes.io/master: ""
  
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

  port: 5030
  service:
    labels: {}
    annotations: {}
    port: 5030

  ingress:
    enabled: true
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
      #kubernetes.io/tls-acme: "true"
    hosts:
    - opennebula-gate.example.org
    tls:
    - secretName: opennebula-tls
      hosts:
      - opennebula-gate.example.org

flow:
  enabled: true
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  replicas: 1

  image:
    repository: docker.io/kvaps/opennebula-flow
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regsecret

  nodeSelector:
    node-role.kubernetes.io/master: ""
  
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

  port: 2474
  service:
    labels: {}
    annotations: {}
    port: 2474

externalNode:
  enabled: false
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

  image:
    repository: docker.io/kvaps/opennebula-node
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regsecret

  nodeSelector:
    node-role.kubernetes.io/master: ""
  
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

  mounts:
