oned:
  enabled: true
  image:
    repository: kvaps/opennebula
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  # nodeSelector:
  #   node-role.kubernetes.io/master: ""
  
  # tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule

  oneadminPasswd: asdasdASD
  serveradminPasswd: vae7thailahh7kiexa2phaipooChah
  oneKey: chaizao3hie1chaiDathaej1puuFoo

  # Database config
  db:
    enabled: true
    backend: mysql
    server: 127.0.0.1
    port: 3306
    user: oneadmin
    passwd: oneadmin
    dbName: opennebula
    connections: 50
    rootPasswd: vahch9saz6ogeaP4ou7P

  service:
    port: 2633

  collectd:
    service:
      port: 32155
      nodePort: 32155

  ingress:
    enabled: true
    labels: {}

    ## Annotations.
    ##
    # annotations: {}
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"


    ## Hostnames.
    ## Must be provided if Ingress is enabled.
    ##
    # hosts: []
    hosts:
      - opennebula.example.org

    ## TLS configuration for Prometheus Ingress
    ## Secret must be manually created in the namespace
    ##
    # tls: []
    tls:
      - secretName: opennebula-tls
        hosts:
          - opennebula.example.org

externalNode:
  mounts:
