oned:
  enabled: true
  image:
    repository: kvaps/opennebula
    tag: v5.8.5
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  # nodeSelector:
  #   node-role.kubernetes.io/master: ""
  
  # tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule

  oneadminPasswd: asdasdASD
  serveradminPasswd: vae7thailahh7kiexa2phaipooChah
  oneKey: chaizao3hie1chaiDathaej1puuFoo

  # Database config
  db:
    enabled: true
    backend: mysql
    server: 127.0.0.1
    port: 3306
    user: oneadmin
    passwd: oneadmin
    dbName: opennebula
    connections: 50
    rootPasswd: vahch9saz6ogeaP4ou7P

  ingress:
    enabled: true

externalNode:
  mounts:
