{{- if .Values.externalNode.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullName }}-external-node
spec:
  selector:
    matchLabels:
      app: {{ $fullName }}-external-node
  template:
    metadata:
      labels:
        app: {{ $fullName }}-external-node
    spec:
      containers:
        image: {{ .Values.externalNode.image.repository }}:{{ .Values.externalNode.image.tag }}
        imagePullPolicy: {{ .Values.externalNode.image.pullPolicy }}
        name: opennebula-node
        command: [ '/bin/bash', '/config/script.sh' ]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /var/lib/one/.ssh
          name: ssh-keys
      hostIPC: true
      hostNetwork: true
      hostPID: true
      {{- with .Values.externalNode.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.externalNode.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.externalNode.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - configMap:
          name: {{ $fullName }}-external-node
        name: config
      - name: ssh-keys
        secret:
          secretName: {{ $fullName }}-ssh-keys
{{- end }}
