{{- if .Values.flow.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-flow
  labels:
    app: {{ $fullName }}-flow
data:
  oneflow-server.conf: |+
    {{- toYaml (mergeOverwrite (fromYaml (tpl (.Files.Get "config/oneflow-server.conf") .)) .Values.flow.configOverrides) | nindent 4 }}
{{- end }}
