{{- if .Values.flow.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-flow
  labels:
    app: {{ $fullName }}-flow
data:
  oneflow-server.conf: |+
    {{- tpl (.Files.Get "config/oneflow-server.conf") . | nindent 4 }}
{{- end }}
