---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opennebula-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opennebula-flow
  template:
    metadata:
      labels:
        app: opennebula-flow
    spec:
      containers:
      - name: oneflow
        image: kvaps/opennebula-flow
        command: [ "/usr/bin/ruby", "/usr/lib/one/oneflow/oneflow-server.rb" ]
        ports:
        - name: http
          containerPort: 2474
        volumeMounts:
        - mountPath: /etc/one/oneflow-server.conf
          name: config
          subPath: oneflow-server.conf
        - mountPath: /var/lib/one/.one/oneflow_auth
          name: one-keys
          subPath: oneflow_auth
      imagePullSecrets:
      - name: regsecret
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        fsGroup: 9869
        runAsUser: 9869
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: config
        configMap:
          name: opennebula-flow
      - name: one-keys
        secret:
          secretName: opennebula-one-keys
      - name: shared
        emptyDir: {}
