{{- if .Values.gate.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-gate
  labels:
    app: {{ $fullName }}-gate
data:
  onegate-server.conf: |+
    {{- toYaml (mergeOverwrite (fromYaml (tpl (.Files.Get "config/onegate-server.conf") .)) .Values.gate.configOverrides) | nindent 4 }}
{{- end }}
