{{- if .Values.gate.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "opennebula.fullname" . }}-gate
data:
  onegate-server.conf: |+
    {{- tpl (.Files.Get "config/onegate-server.conf") . | nindent 4 }}
{{- end }}
