{{- if and .Values.gate.enabled .Values.gate.ingress.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
{{- $servicePort := .Values.gate.service.port -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-gate
  labels:
    app: {{ $fullName }}-gate
{{- if .Values.gate.ingress.labels }}
{{ toYaml .Values.gate.ingress.labels | indent 4 }}
{{- end }}
{{- with .Values.gate.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.gate.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullName }}-gate
          servicePort:  {{ $servicePort }}
  {{- end }}
{{- if .Values.gate.ingress.tls }}
  tls:
{{ toYaml .Values.gate.ingress.tls | indent 4 }}
{{- end }}
{{- end }}
