{{- if .Values.memcached.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-memcached
  labels:
    app: {{ $fullName }}-memcached
    {{- if .Values.memcached.service.labels }}
    {{- toYaml .Values.memcached.service.labels | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: memcached
    port: 11211
  selector:
    app: {{ $fullName }}-memcached
  type: ClusterIP
{{- end }}
