{{- if .Values.memcached.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-memcached
  labels:
    app: {{ $fullName }}-memcached
    {{- if .Values.memcached.labels }}
    {{- toYaml .Values.memcached.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.memcached.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.memcached.replicas }}
  selector:
    matchLabels:
      app: {{ $fullName }}-memcached
  template:
    metadata:
      labels:
        app: {{ $fullName }}-memcached
        {{- with .Values.memcached.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.memcached.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      containers:
      - name: memcached
        image: {{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}
        imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
        ports:
        - name: memcached
          containerPort: 11211
        {{- with .Values.timezone }}
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
          readOnly: true
        {{- end }}
      {{- with .Values.memcached.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.memcached.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.memcached.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      securityContext:
        fsGroup: 9869
        runAsUser: 9869
      {{- with .Values.timezone }}
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/{{ . }}
          type: File
      {{- end }}
{{- end }}
