{{- if .Values.memcached.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-memcached
  labels:
    app: {{ $fullName }}-memcached
    {{- if .Values.memcached.service.labels }}
    {{- toYaml .Values.memcached.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.memcached.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
  - name: memcached
    port: {{ .Values.memcached.service.port }}
  selector:
    app: {{ $fullName }}-memcached
  type: ClusterIP
{{- end }}
