{{- if .Values.novnc.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: opennebula-novnc
  labels:
    app: {{ $fullName }}-novnc
    {{- if .Values.novnc.service.labels }}
    {{- toYaml .Values.novnc.service.labels | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: websocket
    port: {{ .Values.flow.service.port }}
  selector:
    app: {{ $fullName }}-novnc
  type: ClusterIP
{{- end }}
