{{- if .Values.oned.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
{{- $servicePort := .Values.oned.service.port -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned-servers
  labels:
    app: {{ $fullName }}-oned
    {{- if .Values.oned.service.labels }}
    {{- toYaml .Values.oned.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.oned.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: http
    port: {{ $servicePort }}
  selector:
    app: {{ $fullName }}-oned
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned-headless
  labels:
    app: {{ $fullName }}-oned
    {{- if .Values.oned.service.labels }}
    {{- toYaml .Values.oned.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.oned.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: {{ $servicePort }}
  selector:
    app: {{ $fullName }}-oned
    role: leader
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned
  labels:
    app: {{ $fullName }}-oned
    {{- if .Values.oned.service.labels }}
    {{- toYaml .Values.oned.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.oned.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: {{ $servicePort }}
  selector:
    app: {{ $fullName }}-oned
    role: leader
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned-collectd
  labels:
    app: {{ $fullName }}-oned
    {{- if .Values.oned.collectd.service.labels }}
    {{- toYaml .Values.oned.collectd.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.oned.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: collectd
    port: {{ .Values.oned.collectd.port }}
    nodePort: {{ .Values.oned.collectd.service.nodePort }}
    protocol: UDP
  selector:
    app: {{ $fullName }}-oned
  type: NodePort
{{- end }}
