{{- if .Values.oned.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: opennebula-oned-servers
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: http
    port: 2633
  selector:
    app: opennebula-oned
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: opennebula-oned
spec:
  ports:
  - name: http
    port: 2633
  selector:
    app: opennebula-oned
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: opennebula-oned-leader
spec:
  clusterIP: None
  ports:
  - name: http
    port: 2633
  selector:
    app: opennebula-oned
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: opennebula-oned-collectd
spec:
  ports:
  - name: collectd
    nodePort: 32155
    port: 32155
    protocol: UDP
  selector:
    app: opennebula-oned
  type: NodePort
{{- end }}
