{{- if .Values.oned.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
{{- $servicePort := .Values.oned.service.port -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned-servers
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: http
    port: {{ $servicePort }}
  selector:
    app: {{ $fullName }}-oned
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned
spec:
  ports:
  - name: http
    port: {{ $servicePort }}
  selector:
    app: {{ $fullName }}-oned
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned-leader
spec:
  clusterIP: None
  ports:
  - name: http
    port: {{ $servicePort }}
  selector:
    app: {{ $fullName }}-oned
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned-collectd
spec:
  ports:
  - name: collectd
    port: {{ .Values.oned.collectd.service.port }}
    nodePort: {{ .Values.oned.collectd.service.nodePort }}
    protocol: UDP
  selector:
    app: {{ $fullName }}-oned
  type: NodePort
{{- end }}
