{{- if .Values.oned.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-oned
  labels:
    app: {{ $fullName }}-oned
data:
  oned.conf: |+
    {{- tpl (.Files.Get "config/oned.conf") . | nindent 4 }}
{{- end }}
