{{- if .Values.oned.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "opennebula.fullname" . }}-scripts
data:
  init.sh: |+
{{- .Files.Get "scripts/init.sh" | nindent 4 }}
  vip.sh: |+
{{- .Files.Get "scripts/vip.sh" | nindent 4 }}
{{- end }}
