{{- if and .Values.persistence.shared.enabled (not .Values.persistence.shared.existingClaim) }}
{{- $fullName := include "opennebula.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-shared
  labels:
    app: {{ $fullName }}-shared
  annotations:
    helm.sh/resource-policy: "keep"
    {{- with .Values.persistence.shared.annotations  }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.shared.finalizers  }}
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.shared.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.shared.size | quote }}
  storageClassName: {{ .Values.persistence.shared.storageClassName }}
{{- end -}}
