{{- if .Values.sched.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-sched
  labels:
    app: {{ $fullName }}-sched
    {{- if .Values.sched.labels }}
    {{- toYaml .Values.sched.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.sched.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.sched.replicas }}
  selector:
    matchLabels:
      app: {{ $fullName }}-sched
  template:
    metadata:
      labels:
        app: {{ $fullName }}-sched
        {{- with .Values.sched.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/sched-configmap.yaml") . | sha256sum }}
        {{- with .Values.sched.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: sched
        image: {{ .Values.sched.image.repository }}:{{ .Values.sched.image.tag }}
        imagePullPolicy: {{ .Values.sched.image.pullPolicy }}
        command: [ '/usr/bin/mm_sched' ]
        volumeMounts:
        {{- with .Values.timezone }}
        - name: timezone
          mountPath: /etc/localtime
          readOnly: true
        {{- end }}
        - name: config
          mountPath: /etc/one/sched.conf
          subPath: sched.conf
        - name: one-keys
          mountPath: /var/lib/one/.one/one_auth
          subPath: one_auth
      {{- with .Values.sched.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.oned.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oned.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      securityContext:
        fsGroup: 9869
        runAsUser: 9869
      volumes:
      {{- with .Values.timezone }}
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/{{ . }}
          type: File
      {{- end }}
      - name: config
        configMap:
          name: {{ $fullName }}-sched
      - name: one-keys
        secret:
          secretName: {{ $fullName }}-one-keys
{{ end }}
