{{- if .Values.sched.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-sched
  labels:
    app: {{ $fullName }}-sched
data:
  sched.conf: |+
    {{- $mergedConfig := include "opennebula.config" (mergeOverwrite (fromYaml (tpl (.Files.Get "config/sched.conf") .)) .Values.sched.configOverrides) -}}
    {{ $mergedConfig | nindent 4 -}}
{{- end }}
