---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opennebula-sunstone
data:
  sunstone-server.conf: |+
{{- .Files.Get "config/sunstone-server.conf" | nindent 4 }}
  sunstone-views.yaml: |+
{{- .Files.Get "config/sunstone-views.yaml" | nindent 4 }}
  sunstone-logos.yaml: |+
{{- .Files.Get "config/sunstone-logos.yaml" | nindent 4 }}
