{{- if .Values.sunstone.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-sunstone
  labels:
    app: {{ $fullName }}-sunstone
    {{- if .Values.sunstone.service.labels }}
    {{- toYaml .Values.sunstone.service.labels | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: {{ .Values.sunstone.service.port }}
  selector:
    app: {{ $fullName }}-sunstone
  type: ClusterIP
{{- end }}
