{{- if .Values.sunstone.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-sunstone
  labels:
    app: {{ $fullName }}-sunstone
data:
  sunstone-server.conf: |+
    {{- tpl (.Files.Get "config/sunstone-server.conf") . | nindent 4 }}
  sunstone-views.yaml: |+
    {{- tpl (.Files.Get "config/sunstone-views.yaml") . | nindent 4 }}
  sunstone-logos.yaml: |+
    {{- tpl (.Files.Get "config/sunstone-logos.yaml") . | nindent 4 }}
{{- end }}
