{{- if .Values.sunstone.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-sunstone
  labels:
    app: {{ $fullName }}-sunstone
data:
  sunstone-server.conf: |+
    {{- toYaml (mergeOverwrite (fromYaml (tpl (.Files.Get "config/sunstone-server.conf") .)) .Values.sunstone.configOverrides) | nindent 4 }}
{{- end }}
