---
apiVersion: v1
data:

  script.sh: |
    #!/bin/sh
    echo "Connfiguring oneadmin account"
    rm -rf /host-root/var/lib/one/.ssh
    cp -r /var/lib/one/.ssh /host-root/var/lib/one/.ssh
    chown 9869:9869 -R /host-root/var/lib/one/.ssh
    chmod 600 /host-root/var/lib/one/.ssh/id_rsa
    sed -i '/Cmnd_Alias ONE_NET/ {/tcpdump/! s|$|, /usr/sbin/tcpdump|}' /host-root/etc/sudoers.d/opennebula

    echo "Run additional connfiguration"
    #
    # Do some configuration here: eg. connect storages, configre networking
    #
    
    # Sleep forever
    exec tail -f /dev/null
  
kind: ConfigMap
metadata:
  labels:
    ksonnet.io/component: config
  name: opennebula-node
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    ksonnet.io/component: daemonset
  name: opennebula-node
spec:
  selector:
    matchLabels:
      app: opennebula-node
  template:
    metadata:
      labels:
        app: opennebula-node
    spec:
      containers:
      - command:
        - /bin/sh
        - /config/script.sh
        image: alpine
        name: opennebula
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /host-root
          name: host-root
        - mountPath: /config
          name: config
        - mountPath: /var/lib/one/.ssh
          name: oneadmin-ssh-config
      hostIPC: true
      hostNetwork: true
      hostPID: true
      nodeSelector:
        opennebula-node: ""
      volumes:
      - configMap:
          name: opennebula-node
        name: config
      - hostPath:
          path: /
        name: host-root
      - name: oneadmin-ssh-config
        secret:
          secretName: opennebula-ssh-keys
