apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opennebula-appmarket
spec:
  selector:
    matchLabels:
      app: opennebula-appmarket
  serviceName: "opennebula-appmarket"
  replicas: 1
  template:
    metadata:
      labels:
        app: opennebula-appmarket
    spec:
      imagePullSecrets:
      - name: regsecret
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:2
        volumeMounts:
        - name: data
          mountPath: /data/db
      - name: appmarket
        command: [ "/bin/sh", "-c", "sleep 5; exec /usr/bin/ruby /usr/lib/one/ruby/oneapps/market/controllers/appmarket-server.rb" ]
        #command: [ "/bin/sh", "-c", "tail -f /dev/null" ]
        image: registry.wedos.org/opennebula/kube-opennebula/opennebula-appmarket
        ports:
        - containerPort: 6242
          name: web
        volumeMounts:
        - name: config
          mountPath: /etc/one
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: opennebula-appmarket

  #volumeClaimTemplates:
  #- metadata:
  #    name: data
  #  spec:
  #    accessModes: [ "ReadWriteOnce" ]
  #    storageClassName: "my-storage-class"
  #    resources:
  #      requests:
  #        storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: opennebula-appmarket
  labels:
    app: opennebula-appmarket
spec:
  ports:
  - port: 80
    name: web
    targetPort: 6242
  selector:
    app: opennebula-appmarket
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opennebula-appmarket
data:
  appmarket-server.conf: |
    :host: 0.0.0.0
    :port: 6242
    db_host: localhost
    db_port: 27017
    :proxy_path: '/'
    user:
        organization:   default
        first_name:     default
        last_name:      default
        username:       default
        password:       default
        website:        default
        email:          default
  sunstone-appmarket.conf: |
    :appmarket_url: http://localhost:6242
