---
apiVersion: v1
kind: Service
metadata:
  labels:
    ksonnet.io/component: oned
  name: opennebula
spec:
  clusterIP: None
  ports:
  - port: 2633
    targetPort: 2633
  selector:
    app: opennebula-oned
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ksonnet.io/component: oned
  name: opennebula-collectd
spec:
  ports:
  - name: collectd
    nodePort: 32124
    port: 32124
    protocol: UDP
  selector:
    app: opennebula-oned
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    ksonnet.io/component: oned
  name: opennebula-oned
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opennebula-oned
  serviceName: opennebula-oned
  template:
    metadata:
      labels:
        app: opennebula-oned
    spec:
      containers:
      - image: kvaps/opennebula
        name: oned
        ports:
        - containerPort: 2633
        volumeMounts:
        - mountPath: /var/lib/one/.ssh
          name: oneadmin-ssh-keys
        - mountPath: /etc/one/oned.conf
          name: config
          subPath: oned.conf
        - mountPath: /var/lib/one/.one/one_auth
          name: oneadmin-one-keys
          subPath: one_auth
        - mountPath: /var/tmp
          name: data
          subPath: tmp
        - mountPath: /var/log/one
          name: data
          subPath: log
      imagePullSecrets:
      - name: regsecret
      initContainers:
      - command:
        - /bin/sh
        - -c
        - ln -sf /dev/stdout /var/log/one/oned.log
        image: kvaps/opennebula
        name: init
        volumeMounts:
        - mountPath: /var/log/one
          name: data
          subPath: log
      nodeSelector: {}
      securityContext:
        fsGroup: 9869
        runAsUser: 9869
      tolerations: []
      volumes:
      - configMap:
          name: opennebula-oned
        name: config
      - name: oneadmin-ssh-keys
        secret:
          secretName: opennebula-ssh-keys
      - name: oneadmin-one-keys
        secret:
          secretName: opennebula-one-keys
      - emptyDir: {}
        name: data
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  annotations:
#    certmanager.k8s.io/cluster-issuer: letsencrypt
#    kubernetes.io/ingress.class: nginx
#  labels:
#    ksonnet.io/component: oned
#  name: opennebula
#spec:
#  rules:
#  - host: api.opennebula.example.org
#    http:
#      paths:
#      - backend:
#          serviceName: opennebula
#          servicePort: 2633
#  tls:
#  - hosts:
#    - api.opennebula.example.org
#    secretName: opennebula-tls
