---
apiVersion: v1
data:
  onegate-server.conf: |
    :one_xmlrpc: http://opennebula:2633/RPC2
    :host: 0.0.0.0
    :port: 5030
    :ssl_server: https://opennebula-onegate/
    :debug_level: 2
    :auth: onegate
    :core_auth: cipher
    :oneflow_server: http://opennebula-oneflow:2474/
    :permissions:
      :vm:
        :show: true
        :show_by_id: true
        :update: true
        :update_by_id: true
        :action_by_id: true
      :service:
        :show: true
        :change_cardinality: true
    :restricted_attrs:
      - SCHED_REQUIREMENTS
      - SERVICE_ID
      - ROLE_NAME
    :restricted_actions:
      #- deploy
      #- hold
      #- livemigrate
      #- migrate
      #- resume
      #- release
      #- stop
      #- suspend
      #- saveas
      #- snapshot_create
      #- snapshot_revert
      #- snapshot_delete
      #- terminate
      #- reboot
      #- poweroff
      #- chown
      #- chmod
      #- resize
      #- attachdisk
      #- detachdisk
      #- attachnic
      #- detachnic
      #- rename
      #- undeploy
      #- resched
      #- unresched
      #- recover
kind: ConfigMap
metadata:
  labels:
    ksonnet.io/component: onegate-config
  name: opennebula-onegate
