---
apiVersion: v1
kind: Service
metadata:
  labels:
    ksonnet.io/component: onegate
  name: opennebula-onegate
spec:
  ports:
  - port: 5030
    targetPort: 5030
  selector:
    app: opennebula-onegate
  type: ClusterIP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    ksonnet.io/component: onegate
  name: opennebula-onegate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opennebula-onegate
  template:
    metadata:
      labels:
        app: opennebula-onegate
    spec:
      containers:
      - image: kvaps/opennebula-gate
        name: onegate
        ports:
        - containerPort: 5030
        volumeMounts:
        - mountPath: /etc/one/onegate-server.conf
          name: config
          subPath: onegate-server.conf
        - mountPath: /var/lib/one/.one/onegate_auth
          name: oneadmin-one-keys
          subPath: onegate_auth
      imagePullSecrets:
      - name: regsecret
      nodeSelector: {}
      securityContext:
        fsGroup: 9869
        runAsUser: 9869
      tolerations: []
      volumes:
      - configMap:
          name: opennebula-onegate
        name: config
      - name: oneadmin-one-keys
        secret:
          secretName: opennebula-one-keys
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  annotations:
#    certmanager.k8s.io/cluster-issuer: letsencrypt
#    kubernetes.io/ingress.class: nginx
#  labels:
#    ksonnet.io/component: onegate
#  name: opennebula-onegate
#spec:
#  rules:
#  - host: gate.opennebula.example.org
#    http:
#      paths:
#      - backend:
#          serviceName: opennebula-onegate
#          servicePort: 5030
#  tls:
#  - hosts:
#    - gate.opennebula.example.org
#    secretName: opennebula-onegate-tls
