---
apiVersion: v1
data:
  sched.conf: |
    MESSAGE_SIZE = 1073741824
    TIMEOUT      = 60
    ONE_XMLRPC = "http://opennebula:2633/RPC2"
    SCHED_INTERVAL = 30
    MAX_VM       = 5000
    MAX_DISPATCH = 30
    MAX_HOST     = 1
    LIVE_RESCHEDS = 1
    MEMORY_SYSTEM_DS_SCALE = 0
    DIFFERENT_VNETS = YES
    DEFAULT_SCHED = [
        policy = 3,
        rank  = "PRIORITY - RUNNING_VMS"
    ]
    DEFAULT_DS_SCHED = [
        policy = 1
    ]
    DEFAULT_NIC_SCHED = [
        policy = 1
    ]
    LOG = [
        system      = "std",
        debug_level = 5
    ]
kind: ConfigMap
metadata:
  labels:
    ksonnet.io/component: sched-config
  name: opennebula-sched
