---
apiVersion: v1
kind: Service
metadata:
  labels:
    ksonnet.io/component: sunstone
  name: opennebula-sunstone
spec:
  ports:
  - port: 9869
    targetPort: 9869
  selector:
    app: opennebula-sunstone
  type: ClusterIP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    ksonnet.io/component: sunstone
  name: opennebula-sunstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opennebula-sunstone
  template:
    metadata:
      labels:
        app: opennebula-sunstone
    spec:
      containers:
      - image: kvaps/opennebula-sunstone
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - echo 1 > /var/lock/one/.novnc.lock
        name: sunstone
        ports:
        - containerPort: 9869
        volumeMounts:
        - mountPath: /etc/one/sunstone-server.conf
          name: config
          subPath: sunstone-server.conf
        - mountPath: /var/lib/one/.one/sunstone_auth
          name: oneadmin-one-keys
          subPath: sunstone_auth
        - mountPath: /var/tmp
          name: data
          subPath: tmp
        - mountPath: /var/log/one
          name: data
          subPath: log
        - mountPath: /var/lib/one/sunstone_vnc_tokens
          name: data
          subPath: sunstone_vnc_tokens
      imagePullSecrets:
      - name: regsecret
      nodeSelector: {}
      securityContext:
        fsGroup: 9869
        runAsUser: 9869
      tolerations: []
      volumes:
      - configMap:
          name: opennebula-sunstone
        name: config
      - name: oneadmin-one-keys
        secret:
          secretName: opennebula-one-keys
      - emptyDir: {}
        name: data
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  annotations:
#    certmanager.k8s.io/cluster-issuer: letsencrypt
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/proxy-body-size: 5000m
#  labels:
#    ksonnet.io/component: sunstone
#  name: opennebula-sunstone
#spec:
#  rules:
#  - host: opennebula.example.org
#    http:
#      paths:
#      - backend:
#          serviceName: opennebula-sunstone
#          servicePort: 9869
#  tls:
#  - hosts:
#    - opennebula.example.org
#    secretName: opennebula-sunstone-tls
